### ISSUE TITLE
thread 'main' panicked at 'attempted to zero-initialize type `ffi::imp::z::z_stream`, which is invalid'

### ISSUE THREAD

**Issue by d-e-s-o** [ChrisGreenaway/cargo-local-registry#166]
Seeing the following error when running the program on its own `Cargo.lock` (@ 256b9ebbd64fc96c040c3b66e58e7d1865190f0a):
```
$ RUST_BACKTRACE=1 PATH=$PATH:target/debug/ cargo local-registry --sync Cargo.lock /tmp/my-registry
thread 'main' panicked at 'attempted to zero-initialize type `ffi::imp::z::z_stream`, which is invalid', /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/core/src/mem/mod.rs:625:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/core/src/panicking.rs:50:5
   3: core::mem::zeroed
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/core/src/mem/mod.rs:625:9
   4: <flate2::ffi::imp::StreamWrapper as core::default::Default>::default
             at /tmp/cargo-home/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.9/src/ffi.rs:79:42
   5: flate2::mem::Decompress::make
             at /tmp/cargo-home/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.9/src/mem.rs:416:29
   6: flate2::mem::Decompress::new
             at /tmp/cargo-home/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.9/src/mem.rs:390:9
   7: flate2::deflate::bufread::DeflateDecoder<R>::new
             at /tmp/cargo-home/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.9/src/deflate/bufread.rs:186:19
   8: flate2::gz::bufread::GzDecoder<R>::new
             at /tmp/cargo-home/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.9/src/gz/bufread.rs:375:36
   9: flate2::gz::read::GzDecoder<R>::new
             at /tmp/cargo-home/registry/src/github.com-1ecc6299db9ec823/flate2-1.0.9/src/gz/read.rs:142:20
  10: cargo::sources::registry::RegistrySource::unpack_package
             at /tmp/cargo-home/registry/src/github.com-1ecc6299db9ec823/cargo-0.42.0/src/cargo/sources/registry/mod.rs:464:18
  11: cargo::sources::registry::RegistrySource::get_pkg
             at /tmp/cargo-home/registry/src/github.com-1ecc6299db9ec823/cargo-0.42.0/src/cargo/sources/registry/mod.rs:512:20
  12: <cargo::sources::registry::RegistrySource as cargo::core::source::Source>::download
             at /tmp/cargo-home/registry/src/github.com-1ecc6299db9ec823/cargo-0.42.0/src/cargo/sources/registry/mod.rs:609:39
  13: cargo::core::package::Downloads::start_inner
             at /tmp/cargo-home/registry/src/github.com-1ecc6299db9ec823/cargo-0.42.0/src/cargo/core/package.rs:526:19
  14: cargo::core::package::Downloads::start
             at /tmp/cargo-home/registry/src/github.com-1ecc6299db9ec823/cargo-0.42.0/src/cargo/core/package.rs:502:12
  15: cargo::core::package::PackageSet::get_many
             at /tmp/cargo-home/registry/src/github.com-1ecc6299db9ec823/cargo-0.42.0/src/cargo/core/package.rs:439:25
  16: cargo_local_registry::sync
             at ./src/main.rs:157:5
  17: cargo_local_registry::real_main
             at ./src/main.rs:123:5
  18: cargo_local_registry::main
             at ./src/main.rs:90:18
  19: core::ops::function::FnOnce::call_once
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Happens both on debug and release builds, on stable 1.54 and nightly 657bc0188 2021-05-31.

**Comment by ChrisGreenaway** [comment]
Could you describe the steps to reproduce please? In other words, what do you mean by "when running the program on its own Cargo.lock "

**Comment by d-e-s-o** [comment]
```
git clone https://github.com/ChrisGreenaway/cargo-local-registry.git
cd cargo-local-registry/
cargo build --quiet
RUST_BACKTRACE=1 PATH=$PATH:target/debug/ cargo local-registry --sync Cargo.lock /tmp/my-registry
```

**Comment by ChrisGreenaway** [comment]
I can't reproduce this locally.

It's in an FFI call to zlib - so there's probably some platform dependent behaviour involved. What platform are you on?

Given that you are starting to look at cargo as the underlying cause, perhaps you would like to raise a defect there. But, looking at that compilation error, they are probably going to push things to flate2.

**Comment by d-e-s-o** [comment]
Sure, let's close this issue then.
